# Generated by Django 5.2.14 on 2026-05-15 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Generated by Next.js. Format: WC-{timestamp}-{nnnnn}. Used to correlate webhook events back to this row.', max_length=128, unique=True)),
                ('bt_order_id', models.CharField(blank=True, db_index=True, help_text="BT's order id (from 201 response) — or PENDING-{external_id} while a 202 order is being acknowledged.", max_length=128)),
                ('local_status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('unknown', 'Unknown'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('bt_state', models.CharField(blank=True, choices=[('acknowledged', 'Acknowledged'), ('inProgress', 'In progress'), ('held', 'Held'), ('completed', 'Completed'), ('refused', 'Refused'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, help_text='Latest state reported by BT (via webhook). Initially empty.', max_length=32)),
                ('error_message', models.TextField(blank=True, help_text='Most recent BT or internal error. Cleared on successful state advance.')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('billing_street', models.CharField(blank=True, max_length=255)),
                ('billing_house_number', models.CharField(blank=True, max_length=40)),
                ('billing_city', models.CharField(blank=True, max_length=120)),
                ('billing_region', models.CharField(blank=True, max_length=120)),
                ('billing_state', models.CharField(blank=True, max_length=120)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('service_address_id', models.CharField(blank=True, db_index=True, help_text='Openreach NAD id (A...) from the localStorage cart.', max_length=64)),
                ('service_postcode', models.CharField(blank=True, db_index=True, max_length=20)),
                ('service_city', models.CharField(blank=True, max_length=120)),
                ('service_street_name', models.CharField(blank=True, max_length=255)),
                ('service_street_nr', models.CharField(blank=True, max_length=40)),
                ('service_district', models.CharField(blank=True, max_length=8)),
                ('service_qualifier', models.CharField(blank=True, max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_offering_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('contract_term', models.CharField(blank=True, help_text='e.g. 24-months', max_length=32)),
                ('download_speed', models.CharField(blank=True, max_length=16)),
                ('upload_speed', models.CharField(blank=True, max_length=16)),
                ('appointment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('appointment_start', models.DateTimeField(blank=True, null=True)),
                ('appointment_end', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=8)),
                ('coupon_code', models.CharField(blank=True, max_length=64)),
                ('coupon_type', models.CharField(blank=True, help_text='percentage|flat', max_length=16)),
                ('coupon_discount', models.CharField(blank=True, max_length=32)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('other', 'Other')], default='stripe', max_length=16)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField(blank=True, help_text='`createdAt` sent by the browser — kept for audit.', null=True)),
                ('cart_raw', models.JSONField(blank=True, default=list)),
                ('service_address_raw', models.JSONField(blank=True, default=dict)),
                ('billing_address_raw', models.JSONField(blank=True, default=dict)),
                ('shipping_address_raw', models.JSONField(blank=True, default=dict)),
                ('totals_raw', models.JSONField(blank=True, default=dict)),
                ('coupon_raw', models.JSONField(blank=True, default=dict, null=True)),
                ('bt_response_raw', models.JSONField(blank=True, default=dict)),
                ('request_payload_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='orders_bt_email_45d3eb_idx'), models.Index(fields=['bt_state', '-created_at'], name='orders_bt_bt_stat_566ef7_idx'), models.Index(fields=['local_status', '-created_at'], name='orders_bt_local_s_391a4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BTOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('checkout', 'Checkout (initial)'), ('webhook', 'BT webhook'), ('manual', 'Manual'), ('system', 'System')], default='system', max_length=16)),
                ('event_type', models.CharField(blank=True, help_text='e.g. ProductOrderStateChangeEvent, ProductOrderCreationNotification.', max_length=64)),
                ('bt_event_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('sub_code', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('payload_raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Stored even when `order` is null — lets us reconcile orphaned webhooks if the order is created later.', max_length=128)),
                ('order', models.ForeignKey(blank=True, help_text="Null only for orphaned webhooks (BT sent us an externalId we don't have).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.btorder')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['external_id', '-received_at'], name='orders_bt_externa_5f051f_idx')],
            },
        ),
    ]
