# Generated by Django 6.0 on 2026-06-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_btorder_bt_response_raw'),
        ('orders', '0002_rename_orders_bt_email_45d3eb_idx_orders_btor_email_292749_idx_and_more'),
    ]

    operations = [
    ]
