# Generated by Django 6.0 on 2026-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
