# Generated by Django 6.0 on 2026-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
