# Generated by Django 6.0 on 2026-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
            preserve_default=False,
        ),
    ]
