# Generated by Django 6.0 on 2026-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('number_option', models.CharField(blank=True, max_length=100, null=True)),
                ('number_sub_allocation', models.CharField(blank=True, max_length=100, null=True)),
                ('number_import', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('charge_changes', models.JSONField(blank=True, default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed')], default='new', max_length=20)),
            ],
        ),
    ]
