# Generated by Django 6.0 on 2026-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_lines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallineorder',
            name='monthly_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='digitallineorder',
            name='one_off_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='digitallineorder',
            name='total_due_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
