# Generated by Django 6.0 on 2026-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_lines', '0002_digitallineorder_monthly_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallineorder',
            name='addons_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitallineorder',
            name='charge_changes_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitallineorder',
            name='equipment_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitallineorder',
            name='plan_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
