# Generated by Django 6.0 on 2026-06-25 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('issue_type', models.CharField(max_length=100)),
                ('is_business_customer', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('public', 'Public Building'), ('other', 'Other')], max_length=50)),
                ('problem_description', models.TextField()),
                ('related_issues', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('post', 'Post')], max_length=20)),
                ('survey_needed', models.CharField(choices=[('required', 'Required'), ('not_required', 'Not Required')], max_length=20)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Engineer Assigned'), ('investigating', 'Investigation In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=30)),
                ('engineer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='fault.faultreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
