# Generated by Django 6.0 on 2026-05-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerequest',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
