# Generated by Django 6.0 on 2026-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_requests', '0003_alter_bundlerequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerequest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
