# Generated by Django 6.0 on 2026-04-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planvariation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='planvariation',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='planvariation',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price (overrides regular price)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Plan Name'),
        ),
    ]
