# Generated by Django 6.0 on 2026-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_planvariation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
