# Generated by Django 6.0 on 2026-04-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_planvariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planvariation',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
