# Generated by Django 6.0 on 2026-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_vcplanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_24',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
