# Generated by Django 6.0 on 2026-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBroadbandInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_postcode', models.CharField(max_length=20)),
                ('business_size', models.CharField(choices=[('1-10 employees', '1-10 employees'), ('11-50 employees', '11-50 employees'), ('50+ employees', '50+ employees')], max_length=50)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
