# Generated by Django 6.0 on 2026-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_broadband', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbroadbandinquiry',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
